name: Sync Obsidian posts

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "src/posts/**"

permissions:
  contents: write

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Obsidian repo
        uses: actions/checkout@v4
        with:
          repository: gustavodscruz/obsidian-notes
          path: obsidian
          token: ${{ secrets.OBS_TOKEN }}

      - name: Copy posts
        run: |
          rm -rf src/posts
          mkdir -p src/posts
          cp -r obsidian/portfolio/posts/* src/posts/

      - name: Commit and push posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add src/posts

          git diff --cached --quiet || git commit -m "chore: sync posts from Obsidian"

          git push origin HEAD
