name: "Clone Obsidian repo"

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  clone-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Obsidian repo
        uses: actions/checkout@v4
        with:
          repository: gustavodscruz/obsidian-notes
          path: obsidian
          token: ${{ secrets.OBS_TOKEN }}
          persist-credentials: true

      - name: Copy posts
        run: |
          rm -rf src/posts
          mkdir -p src/posts
          cp -r obsidian/portfolio/posts/* src/posts/

      - name: Commit and push posts
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add origin https://github.com/${{ github.repository }}.git

          git branch -M develop
          git add src/posts
          git diff --quiet || git commit -am "chore: sync posts"
          git push origin develop
